// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package txnpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TxnServiceClient is the client API for TxnService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TxnServiceClient interface {
	// Sends a greeting
	CreateTxn(ctx context.Context, in *TxnRequest, opts ...grpc.CallOption) (*TxnResponse, error)
}

type txnServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTxnServiceClient(cc grpc.ClientConnInterface) TxnServiceClient {
	return &txnServiceClient{cc}
}

func (c *txnServiceClient) CreateTxn(ctx context.Context, in *TxnRequest, opts ...grpc.CallOption) (*TxnResponse, error) {
	out := new(TxnResponse)
	err := c.cc.Invoke(ctx, "/TxnService/CreateTxn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TxnServiceServer is the server API for TxnService service.
// All implementations must embed UnimplementedTxnServiceServer
// for forward compatibility
type TxnServiceServer interface {
	// Sends a greeting
	CreateTxn(context.Context, *TxnRequest) (*TxnResponse, error)
	mustEmbedUnimplementedTxnServiceServer()
}

// UnimplementedTxnServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTxnServiceServer struct {
}

func (UnimplementedTxnServiceServer) CreateTxn(context.Context, *TxnRequest) (*TxnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTxn not implemented")
}
func (UnimplementedTxnServiceServer) mustEmbedUnimplementedTxnServiceServer() {}

// UnsafeTxnServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TxnServiceServer will
// result in compilation errors.
type UnsafeTxnServiceServer interface {
	mustEmbedUnimplementedTxnServiceServer()
}

func RegisterTxnServiceServer(s grpc.ServiceRegistrar, srv TxnServiceServer) {
	s.RegisterService(&TxnService_ServiceDesc, srv)
}

func _TxnService_CreateTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TxnServiceServer).CreateTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TxnService/CreateTxn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TxnServiceServer).CreateTxn(ctx, req.(*TxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TxnService_ServiceDesc is the grpc.ServiceDesc for TxnService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TxnService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TxnService",
	HandlerType: (*TxnServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTxn",
			Handler:    _TxnService_CreateTxn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "txn.proto",
}
